sudo: required
services:
  - docker

language: generic

before_install:
  - docker build -t haytham/docker-react -f Dockerfile.dev .

- script:
  - docker run -e CI=true haytham/docker-react npm run test